name: Deploy Lambda con OIDC

on:
  push:
    branches:
      - main

permissions:
  id-token: write    # necesario para OIDC
  contents: read     # para clonar tu repo

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del repositorio
        uses: actions/checkout@v4

      - name: Configurar credenciales AWS vía OIDC
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::711615380364:role/OIDC-Lambda
          aws-region: us-east-1

      - name: Subir código a Lambda
        run: |
          aws lambda update-function-code \
            --function-name mi-funcion-dev \
            --zip-file fileb://lambda.zip \
            --publish
