name: Prune All Lambda Versions
on:
  schedule:
    - cron: '13 15 * * 1'  # Diario a medianoche UTC
  workflow_dispatch:
permissions:
  id-token: write    # necesario para OIDC
  contents: read     # para clonar tu repo
jobs:
  prune-all:
    runs-on: ubuntu-latest
    steps:
      - name: Configurar credenciales AWS (OIDC)
        uses: aws-actions/configure-aws-credentials@v4.1.0
        with:
          role-to-assume: arn:aws:iam::711615380364:role/OIDC-Lambda
          aws-region: us-east-1

      - name: Listar y podar versiones de todas las Lambdas
        run: |
          FUNCTIONS=$(aws lambda list-functions --output text --query 'Functions[].FunctionName')
          for FN in $FUNCTIONS; do
            VERSIONS=($(aws lambda list-versions-by-function --function-name "$FN" --output text --query 'Versions[].Version'))
            ALIAS_VERSIONS=($(aws lambda list-aliases --function-name "$FN" --output text --query 'Aliases[].FunctionVersion'))
            
            SORTED=($(printf "%s\n" "${VERSIONS[@]}" | sort -n))
            
            KEEP=0
            COUNT=${#SORTED[@]}
            
            for (( i=0; i<COUNT-KEEP; i++ )); do
                aws lambda delete-function --function-name "$FN" --qualifier "$VER"
            done
          done
